services:
  agent:
    build: .
    container_name: containerguard-agent
    command: python agent/runner.py
    volumes:
      - containerguard-data:/app/data
      - /tmp:/tmp
    environment:
      - DOCKER_HOST=tcp://192.168.217.163:2375
      - AGENT_INTERVAL=30
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - containerguard-net

  dashboard:
    build: .
    container_name: containerguard-dashboard
    command: python dashboard/app.py
    ports:
      - "7860:7860"
    volumes:
      - containerguard-data:/app/data
      - /tmp:/tmp
    environment:
      - DOCKER_HOST=tcp://192.168.217.163:2375
      - AGENT_INTERVAL=30
      - LOG_LEVEL=INFO
    restart: unless-stopped
    depends_on:
      - agent
    networks:
      - containerguard-net

volumes:
  containerguard-data:
    driver: local

networks:
  containerguard-net:
    driver: bridge
